### ISSUE TITLE
SWB launched RStudio instance failed to create public_key

### ISSUE THREAD

**Issue by anthony-watkins** [RLOpenCatalyst/Service_Workbench_Templates#13]
After building the RStudio ami and registering the workspace in SWB, it successfully launches but the connect button shows an error.

After more investigation it appears the public key is never written to the ssm parameter store. Launching new instances, restarting the existing instances, and including a wait condition doesn't appear to resolve the problem.

SWB is launched in a main account while the RStudio instance is launched in a host account, both using the us-east-2 region.

Let me know if there's any other details I can provide to help track down the problem. Thanks in advance.

**Comment by venkatch4** [comment]
Is this resolved. I amf acing same issue.
