### ISSUE TITLE
[Question] Target Groups per Application Load Balancer Quota

### ISSUE THREAD

**Issue by srpiatt** [RLOpenCatalyst/Service_Workbench_Templates#18]
Has anyone encountered hitting the load balancer quota limit for RStudio instances? I was looking in the AWS console, and noticed that the quota for target groups is not adjustable. I assume that when you hit that limit, it would probably fail to launch instances. 

How would we get around this limit, if it became an issue?

<img width="1138" alt="Screen Shot 2023-02-02 at 2 05 39 PM" src="https://user-images.githubusercontent.com/21109191/216428195-3bf06e75-426e-4347-a7be-79c4f1707721.png">

**Comment by srpiatt** [comment]
As an update-- yes it does fail to launch instances, as we just hit this limit yesterday in a production environment. Please advise.

**Comment by mamatha-anand** [comment]
Hi - This is a known design issue based on AWS ALB Routing Groups limitation of 100 (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html) and this is related to no. of RStudio Instances (Running or Stopped). The workaround to this is to create projects linked to different Accounts (AWS Account + Region) each having an ALB with 100 connections. Alternate is to change design to support cluster of ALBs but that will require customization at code level.
