### ISSUE TITLE
Workspace not loading

### ISSUE THREAD

**Issue by paolosach** [RLOpenCatalyst/Service_Workbench_Templates#19]
Description of the bug
When we create a workspace with Rstudio, once the workspace is available, we click on connect and a error message pop up on the bottom right on the screen: “something went wrong”.

To Reproduce

1. Go to ‘workspaces’
2. Click on ‘create research workspace’
3. Select EC2-RStudio-Server, RStudio Server version 1.4.1717
4. When the workspace appears as “Available” click on “connect”
5. Then on the workspace page the error "something when wrong" appears.

The browser console shows a 500 code error
![Screen Shot 2023-02-20 at 11 16 23](https://user-images.githubusercontent.com/55581406/220077476-ced71b27-cc5f-4357-ac50-30f9abd95b97.png)

![Screen Shot 2023-02-20 at 10 58 16](https://user-images.githubusercontent.com/55581406/220076711-5c55424f-a0bd-4301-9388-8ec8bd4e1e71.png)

**Comment by mamatha-anand** [comment]
Hi - To debug this  further, request to please send a mail to our Support ID - rlcloudsupport@relevancelab.com with more details or you can share your email ID with us to get you added to our Support Slack Channel.

**Comment by mamatha-anand** [comment]
Hi - As we have not heard from you, we are closing this issue. If you are facing any issues, please send a mail to our Support ID  - rlcloudsupport@relevancelab.com with complete details.
