### ISSUE TITLE
EC2-RStudio-Server 1.4.1717 from AWS Marketplace is not compatible with new versions of Service Workbench

### ISSUE THREAD

**Issue by BoPeng** [RLOpenCatalyst/Service_Workbench_Templates#21]
Also reported at https://github.com/awslabs/service-workbench-on-aws/issues/1146

**Describe the bug**
When starting a workspace with EC3-RStudio-Server 1.4.1717 from AWS Marketplace, it fails with an error message for missing parameter `IsAppStreamEnabled`.

**To Reproduce**
1. Go to AWS Marketplace, subscribe the EC2-RStudio-Server
2. Copy to Service Catalog,  fix a version description bug (#1143 ) and import RStudio Server
3. Create a configuration, create a workspace

**Expected behavior**
RStudio should start, but it fails with missing parameter for cloudformation

**Screenshots**

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/9889312/225056186-79c517b3-e536-438b-9cf6-42831595083e.png">

**Comment by mamatha-anand** [comment]
Hi - Based on the response to similar issue raised in AWS repo -  https://github.com/awslabs/service-workbench-on-aws/issues/1146 , this was due to parameters configuration mismatch. Post configuring the same , issue stands resolved.

Hence we are closing this bug. In case if you are still have any queries/clarifications, request to please drop an email to rlcloudsupport@relevancelab.com.

**Comment by BoPeng** [comment]
The issue is not completely resolved. After adding those three parameters, I could start Rstudio server but I do not see the "connect" button,

![image](https://user-images.githubusercontent.com/9889312/225388665-11697a13-ea7f-4731-8d53-d2fe70414e58.png)

The Edit CIDRs button shows

![image](https://user-images.githubusercontent.com/9889312/225388764-66bfee20-7b79-4537-8f7b-9888b097dc83.png)

It must have been something wrong with my network setting, 

![image](https://user-images.githubusercontent.com/9889312/225389005-c32e73fb-3716-49a9-bcec-ea4abb957f43.png)

![image](https://user-images.githubusercontent.com/9889312/225389044-27e6c33a-553c-4a83-b017-0a471bc8e672.png)

so I checked the instance:

![image](https://user-images.githubusercontent.com/9889312/225389420-c56d067a-ce39-422d-acd9-91361793368a.png)

and the instance can be accessed using the public IP

![image](https://user-images.githubusercontent.com/9889312/225389552-2857c964-e255-40e1-868c-434e78ffcf7f.png)

The security group looks ok

![image](https://user-images.githubusercontent.com/9889312/225389715-a5fdb381-17cc-43b8-9812-e77da41f7ecd.png)


@mamatha-anand what else should I check?

**Comment by BoPeng** [comment]
It may be easier to update the AWS Marketplace with the latest version of the AMI instead of fixing the template for this outdated version.
